version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: iit
      POSTGRES_USER: iit
    volumes: 
      - ./init_test_db.sql:/docker-entrypoint-initdb.d/init_test_db.sql
    ports:
    - 5432:5432
