CREATE SCHEMA iit
    AUTHORIZATION iit;

CREATE ROLE iit_test WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'iit_test';

CREATE DATABASE iit_test
    WITH 
    OWNER = iit_test
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

\connect iit_test;

CREATE SCHEMA iit
    AUTHORIZATION iit_test;